# Generated by Django 2.0.13 on 2019-03-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaicon')),
                ('name_assignature', models.CharField(max_length=255, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaicon')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo de Carrera')),
                ('description', models.TextField(verbose_name='Descripción de la Carrera')),
                ('image', models.ImageField(upload_to='carrers', verbose_name='Imagen Representativa')),
            ],
            options={
                'verbose_name': 'carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaicon')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Categoria')),
            ],
            options={
                'ordering': ['-created', 'updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationCarrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaicon')),
                ('requirements', models.TextField(verbose_name='Requerimientos')),
                ('costos', models.TextField(verbose_name='Costos')),
                ('student_profile', models.TextField(verbose_name='Perfil del estudiante')),
                ('carrer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrers.Carrer')),
            ],
            options={
                'verbose_name': 'Informacion de la carrera',
                'verbose_name_plural': 'Informacion sobre las carreras',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaicon')),
                ('number_semester', models.IntegerField(verbose_name='Numero de Semestre')),
                ('semester_name', models.CharField(max_length=240, verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['number_semester'],
            },
        ),
        migrations.AddField(
            model_name='carrer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrers.Category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='asignature',
            name='carrer',
            field=models.ManyToManyField(related_name='get_carrer', to='carrers.Carrer', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='asignature',
            name='cicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrers.Semester', verbose_name='Semestre Asignado'),
        ),
    ]
