# Generated by Django 2.0.13 on 2019-03-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='image',
            field=models.ImageField(default=2, upload_to='events', verbose_name='Imagen Representativa'),
            preserve_default=False,
        ),
    ]
