# Generated by Django 2.0.13 on 2019-03-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventmodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ['-date_init'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
