# Generated by Django 2.0.13 on 2019-03-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190331_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
