# Generated by Django 2.0.13 on 2019-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaicon')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo del premio')),
                ('image', models.ImageField(upload_to='awards/icons', verbose_name='Icono referencial')),
                ('description', models.TextField(verbose_name='Descripcion del premio')),
                ('date', models.DateField(help_text='Fecha que se otorgo el reconocimiento')),
            ],
            options={
                'verbose_name': 'Premios',
                'verbose_name_plural': 'Premios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaicon')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo del deparamento')),
                ('image', models.ImageField(upload_to='facilities/img', verbose_name='Imagen referencial')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaicon')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo de la ayuda')),
                ('image', models.ImageField(upload_to='facilities/img', verbose_name='Imagen referencial')),
                ('description', models.TextField(verbose_name='Descripcion de la ayuda')),
            ],
            options={
                'verbose_name': 'Facilidad y Ayuda',
                'verbose_name_plural': 'Facilidades y Ayudas',
                'ordering': ['-created'],
            },
        ),
    ]
