# Generated by Django 2.0.13 on 2019-03-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190331_0310'),
        ('admision', '0002_admisioncarrer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmisionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaicon')),
                ('first_name', models.CharField(max_length=70, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=70, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=20, verbose_name='Numero Telefonico')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventModel', verbose_name='Carrera Solicitada')),
            ],
            options={
                'verbose_name': 'Admision de Carrera',
                'verbose_name_plural': 'Admisiones de Carrera',
                'ordering': ['-created'],
            },
        ),
    ]
