# Generated by Django 2.0.13 on 2019-03-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0003_admisionevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admisionevent',
            options={'ordering': ['-created'], 'verbose_name': 'Admision de Evento', 'verbose_name_plural': 'Admisiones de Evento'},
        ),
    ]
