# Generated by Django 2.0.13 on 2019-04-03 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0004_auto_20190331_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admisioncarrer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +9999999999. Up to 20 digits', regex='\\+?1?\\d{9,15}')], verbose_name='Numero Telefonico'),
        ),
    ]
