# Generated by Django 2.0.13 on 2019-03-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/post', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
